alert("Welcome to Sol@ce - Brings Comfort to Life")
alert("Error! Please enter a valid password.")
alert("Welcome to JS Land...\nHappy Coding!")
alert("Welcome to JS Land...")
alert("Happy Coding!\nPrevent this page from creating additional dialogs.")